export default {
	THEME_CHANGE:'THEME_CHANGE',
	THEME_INIT:'THEME_INIT',
	POPULAR_REFRESH:'POPULAR_REFRESH',//Popular页面加载数据
	LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',//Popular页面加载数据失败
	LOAD_POPULAR_SUCCESS:'LOAD_POPULAR_SUCCESS'//Popular页面加载数据成功
}